default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: staytuned_development

test:
  <<: *default
  database: staytuned_test

production:
  <<: *default
  database: staytuned_production
  url: <%= ENV['DATABASE_URL'] %>
